Repository d0mi04/stable-management-system, pull requests merged in 2025-06, with the labels that each got.

#5 added route-based control and created additional pages and components
  client/client/src/App.js
  client/client/src/components/AdminLayout.jsx
  client/client/src/components/PrivateRoute.jsx
  client/client/src/components/UserLayout.jsx
  client/client/src/context/AuthContext.jsx
  client/client/src/context/StableContext.jsx
  client/client/src/pages/Dashboard.jsx
  client/client/src/pages/Expenses.jsx
  client/client/src/pages/HorseDetails.jsx
  client/client/src/pages/Horses.jsx
  client/client/src/pages/Login.jsx
  client/client/src/pages/Schedule.jsx
  client/client/src/pages/Settings.jsx
  client/client/src/pages/Stables.jsx
  client/client/src/pages/Staff.jsx
  client/client/src/pages/Unauthorized.jsx
  client/client/src/pages/UserHome.jsx
Labels: enhancement

#6 feature(layout): added logout button for admin and user
  client/client/src/components/AdminLayout.jsx
  client/client/src/components/UserLayout.jsx
  client/client/src/context/AuthContext.jsx
Labels: enhancement

#10 add HorseTableComponent to list horses
  client/client/src/App.js
  client/client/src/pages/Horses.jsx
  client/client/src/pages/admin/Horses/HorseTable.jsx
Labels: enhancement

#13 styling HorseTable layout
  client/client/public/resources/photos/horse-placeholder.jpg
  client/client/src/pages/admin/Horses/HorseStyles.css
  client/client/src/pages/admin/Horses/HorseTable.jsx
Labels: style

#16 fixing Stall schema
  server/server/models/Stall.js
Labels: fix

#17 Feature/auth middleware
  server/server/controllers/authController.js
  server/server/middleware/authMiddleware.js
  server/server/models/User.js
  server/server/package-lock.json
  server/server/package.json
  server/server/routes/auth.js
  server/server/server.js
Labels: enhancement

#18 update README.md
  README.md
Labels: documentation

#19 Backend/schema controllers routings
  server/server/controllers/authController.js
  server/server/controllers/expenseController.js
  server/server/controllers/horseActivityController.js
  server/server/controllers/horseController.js
  server/server/controllers/stableController.js
  server/server/controllers/staffController.js
  server/server/middleware/authMiddleware.js
  server/server/models/Expense.js
  server/server/models/Horse.js
  server/server/models/Stall.js
  server/server/models/User.js
  server/server/routes/expenses.js
  server/server/routes/horseActivities.js
  server/server/routes/horses.js
  server/server/routes/stables.js
  server/server/routes/staff.js
  server/server/server.js
Labels: enhancement

#20 Documentation/docs
  docs/auth-system.md
  docs/horse-module.md
Labels: documentation

#22 fixing security - only logged in user can retrieve horses GET /horses
  server/server/routes/horses.js
Labels: fix

#24 no events displayed fixed
  server/server/routes/events.js
Labels: fix

#38 add DELETE /stables/:stableID endpoint logic
  server/server/controllers/stableController.js
  server/server/routes/stables.js
Labels: fix
